[package]
name = "quotient-filter"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "Apache-2.0"
publish = false

[dependencies]
quotient-accountant-core = { path = "../quotient-accountant-core" }
quotient-odometer = { path = "../quotient-odometer" }

[workspace]

[lints.rust]
unsafe_code = "forbid"
